name: "Example Action"
description: "This values need to be changed"
author: Bullrich
branding:
  icon: copy
  color: yellow
inputs:
  commands-directory:
    required: false
    description: The directory where the command scripts are available
    default: "./github/commands"
outputs:
  repo:
    description: 'The name of the repo in owner/repo pattern'
  commands:
    description: "An array of commands to execute"

runs:
  using: 'docker'
  image: 'Dockerfile'
