name: 'run-cmd'
description: 'Run command'
inputs:
  branch:  # id of input
    description: 'Branch name'
    required: true
  command:
    description: "Command to be run"
    required: true
  pr-number:
    description: "Number of the PR"
    required: true
runs:
  using: "composite"
  steps:
      - name: Download repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - name: Generate script
        shell: bash
        # Here it would get the script from previous step
        run: bash -c "$COMMAND"
        env:
          COMMAND: ${{ inputs.command }}
      - name: Report failure
        if: ${{ failure() }}
        shell: bash
        run: gh pr comment ${{ inputs.pr-number }} --body "Run for `${{ inputs.command}}` failed. See logs <a href=\"$RUN\">here</a>."
        env:
          RUN: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          GH_TOKEN: ${{ github.token }}
