name: Continuous testing

on: 
  pull_request:
  push:
    branches: ["main"]

jobs:
  test:
    strategy:
      matrix:
        command: [lint, build, test]
    runs-on: ubuntu-latest
    name: running ${{ matrix.command }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - run: yarn run ${{ matrix.command }}

  conclude:
    runs-on: ubuntu-latest
    name: All tests passed
    needs: [test]
    steps:
      - run: echo '### Good job! All the tests passed 🚀' >> $GITHUB_STEP_SUMMARY
